### PR TITLE
Removed testing dependency

### LINKED ISSUE #2: Make an npm from this repo
* Npm
* github actions to build
* github action on release to send it to npm

### PR DESCRIPTION
**Pull request by abroa01**
Removed testing dependency as this package has been tested locally using npm link.

### CODE REVIEW

**Review by horner — CHANGES_REQUESTED** [review]
I would leave the testing dependency, but change the test so it returns passed.

**Comment by wreiske** [comment]
What is your reasoning for removing it? We don't want to publish broken code to NPM. Ensuring the test passes successfully before pushing to NPM is a critical step in ci/cd

**Review by wreiske — CHANGES_REQUESTED** [review]
We should not remove testing from CI / CD.

**Comment by horner** [comment]
The test requires a webchart system. I asked him to remove the dependency on webchart. I think the test should do something that can be done completely independent and later will simulate a WebChart system.

**Comment by abroa01** [comment]
Hi Will,

- Removed test cases with WebChart dependencies and sensitive info (username, password, practice).
- Used sinon to mock functionality, avoiding external system calls.
- Added basic test cases to validate core functionality (initialization, session management, method definitions).

**Comment by wreiske** [comment]
Awesome! Can you do me one last favor? It would be good to have the pull request run the npm test, that way we can make sure the tests are passing before merging into the main branch. You can add a second workflow file named "check-pull-request" and set the on to push.

https://medium.com/marionete/using-github-actions-to-help-review-pull-requests-using-unit-tests-and-code-coverage-72bde49ed3a2

**Comment by abroa01** [comment]
Hey Will,

I have added a GitHub actions to test the Pull request and run all the tests before merging it.

Can you please check if that fine or any change is needed.

**Review by horner — APPROVED** [review]

**Pull request merged**
